# fly.toml app configuration file generated for withered-smoke-1752 on 2023-05-29T15:08:44+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "withered-smoke-1752"
primary_region = "ams"

[http_service]
  internal_port = 25
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
